### ISSUE TITLE
Could ObservableMap#keySet() yield an ObservableSet?

### ISSUE THREAD

**Issue by SkytAsul** [Osmerion/Quitte#11]
Is it even something that could be done in the future or would it be too complicated to implement?

**Comment by TheMrMilchmann** [comment]
Sounds doable on first thought. I'll look into it.

**Comment by TheMrMilchmann** [comment]
Hey @SkytAsul, sorry for the long delay. I've made the necessary changes in 027ab4c59e2d8c7935061eb4c2c1f9308a2cb3fc and aim to release `0.8.0` by next week.

**Comment by SkytAsul** [comment]
Wow that's awesome, thank you!!

**Comment by SkytAsul** [comment]
I've started to use 0.8.0 last week, I love the changes in the observable collections so far! It's been a little tedious to migrate but now it's done, that's cool :)
