### ISSUE TITLE
Expose AbstractObjectExpression<T> as an usable class

### ISSUE THREAD

**Issue by SkytAsul** [Osmerion/Quitte#9]
Just like in https://github.com/Osmerion/Quitte/issues/4.

`AbstractObjectExpression` is a sealed class due to its package-private constructor. I would personally like to extend this class and can't see any reason why it would be sealed.

My goal here is basically to create a new "set" of observables/properties/expression types for Component objects, a class similar to String. As I have to make a _lot_ of different properties and expressions for this Component, I don't want to be using this much `WritableObjectProperty<Component>`, `SimpleObjectExpression<Component>`... hence I created my own: properties types
![image](https://user-images.githubusercontent.com/28827134/209443920-a7b308d1-31c9-4976-adba-398023f9c31e.png)
But now I'm in trouble for the expression one, as I want to extend `AbstractObjectExpression` but I can't.
I could extend `AbstractExpression`, but I'd have to do a lot of copy-paste...

**Comment by TheMrMilchmann** [comment]
Did you consider extending `SimpleObjectExpression` (or `LazyObjectExpression`) instead? If yes, what issues did you face? I'm considering hiding the `Abstract${Type}Expression` classes fully from the API as these are just implementation details.

**Comment by SkytAsul** [comment]
It's only a really small problem: if my `SimpleComponentExpression` class extends `SimpleObjectExpression`, then it will also inherit all of the utility static methods in `SimpleObjectExpression`. In the devs IDEs, when they will fetch autocompletion for `SimpleComponentExpression.###`, they will get all the `SimpleObjectExpression` ones, which they don't care.
That's all, yeah it's ridiculous 😅 but as I think I might not be the only one that wants to create a full set of observables for a custom type, I asked.

**Comment by TheMrMilchmann** [comment]
I don't think that this is too big of a problem and, after putting further thought into it, I concluded that I don't want to expose these abstract classes for the previously stated reason.

Ideally, you will probably want to declare the static utility methods in your `SimpleComponentExpression` for symmetry with Quitte's classes. If you do that, the superclass's utility methods should be effectively hidden and no longer be accessible (via `SimpleComponentExpression`). Additionally, even if you do not implement them, the methods will still work correctly (although the return type may not be what you'd prefer).
